# Generated by Django 6.0.3 on 2026-03-10 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('reports', '0001_initial'),
        ('services', '0002_division_alter_blockeddate_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='report',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='report',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='services.service'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.CharField(choices=[('fraud', 'Fraud'), ('abuse', 'Abuse'), ('inappropriate_content', 'Inappropriate Content'), ('misbehavior', 'Misbehavior'), ('other', 'Other')], max_length=50),
        ),
    ]
