# Generated by Django 6.0.3 on 2026-03-10 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='message',
            name='subject',
        ),
    ]
